version: "3"

services:
  dogschaindnode0:
    container_name: dogschaindnode0
    image: "dogschaind/node"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
    environment:
      - ID=0
      - LOG=${LOG:-dogschaind.log}
    volumes:
      - ./build:/dogschain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2
    entrypoint: "bash start.sh"

  dogschaindnode1:
    container_name: dogschaindnode1
    image: "dogschaind/node"
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
      - "8547:8545"
      - "8548:8546"
    environment:
      - ID=1
      - LOG=${LOG:-dogschaind.log}
    volumes:
      - ./build:/dogschain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3
    entrypoint: "bash start.sh"

  dogschaindnode2:
    container_name: dogschaindnode2
    image: "dogschaind/node"
    environment:
      - ID=2
      - LOG=${LOG:-dogschaind.log}
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
      - "8549:8545"
      - "8550:8546"
    volumes:
      - ./build:/dogschain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4
    entrypoint: "bash start.sh"

  dogschaindnode3:
    container_name: dogschaindnode3
    image: "dogschaind/node"
    environment:
      - ID=3
      - LOG=${LOG:-dogschaind.log}
    ports:
      - "26663-26664:26656-26657"
      - "1320:1317"
      - "8551:8545"
      - "8552:8546"
    volumes:
      - ./build:/dogschain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5
    entrypoint: "bash start.sh"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
